openapi: 3.0.2
info:
  title: LojaAPI
  version: '1.0'
servers:
  - url: https://api.minhaloja.com/v1

paths:
  /produtos:
    get:
      summary: Lista todos os produtos disponíveis
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'

  /pedidos:
    get:
      summary: Lista os pedidos realizados
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'

    post:
      summary: Cria um novo pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pedido'
      responses:
        '201':
          description: Pedido criado com sucesso
        '400':
          description: Dados inválidos

components:
  schemas:

    Produto:
      type: object
      required:
        - id
        - nome
        - preco
      properties:
        id:
          type: integer
        nome:
          type: string
        preco:
          type: number
          format: float

    ItemPedido:
      type: object
      required:
        - produtoId
        - quantidade
      properties:
        produtoId:
          type: integer
        quantidade:
          type: integer

    Pedido:
      type: object
      required:
        - id
        - data
        - itens
      properties:
        id:
          type: integer
        data:
          type: string
          format: date
        itens:
          type: array
          items:
            $ref: '#/components/schemas/ItemPedido'