// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace MinhaLoja.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Pedido : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
        public Date? Data { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The itens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MinhaLoja.Client.Models.ItemPedido>? Itens { get; set; }
#nullable restore
#else
        public List<global::MinhaLoja.Client.Models.ItemPedido> Itens { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MinhaLoja.Client.Models.Pedido"/> and sets the default values.
        /// </summary>
        public Pedido()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MinhaLoja.Client.Models.Pedido"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MinhaLoja.Client.Models.Pedido CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MinhaLoja.Client.Models.Pedido();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetDateValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "itens", n => { Itens = n.GetCollectionOfObjectValues<global::MinhaLoja.Client.Models.ItemPedido>(global::MinhaLoja.Client.Models.ItemPedido.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("data", Data);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::MinhaLoja.Client.Models.ItemPedido>("itens", Itens);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
